### ISSUE TITLE
Support for Multiple SAML2 Instances

### ISSUE THREAD

**Issue by elrapha** [pac4j/ratpack-pac4j-demo#12]
I am new to ratpack and am wondering how the implementation will look like if one had multiple SAML2 instances to support. How will one manage the sessions? is this even possible with pac4j?

https://github.com/pac4j/ratpack-pac4j-demo/blob/f307934bafd7d702a4d8e533e025ca60e4166dff/src/main/java/org/pac4j/demo/ratpack/RatpackPac4jDemo.java#L99

**Comment by leleuj** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
