### ISSUE TITLE
Refreshing idp metadata

### ISSUE THREAD

**Issue by elrapha** [pac4j/ratpack-pac4j-demo#15]
How do i refresh the idp metadata. I tried calling theClient.getIdentityProviderMetadataResolver().resolve() but that does not download a new idp metadata. What am i missing?

I am using the SAML 2.0 implementation and everything works so far except for the refreshing part. The idp i am pointing to expires so i need to be able to refresh the data

**Comment by leleuj** [comment]
Please use the mailing lists for questions: http://www.pac4j.org/mailing-lists.html

In short, you can't. You need to download the IdP metadata again.
