### ISSUE TITLE
How to specify the relayState for SAML2

### ISSUE THREAD

**Issue by elrapha** [pac4j/ratpack-pac4j-demo#16]
It is not clear to me how to handle the relay state after login.
Where is the relaystate param to be set. How do i get the relay state to be returned by sessionData.get(Pac4jSessionKeys.REQUESTED_URL)

I see that this is used at Pac4jAuthenticator.java:74

**Comment by leleuj** [comment]
Please use the mailing list for questions: http://www.pac4j.org/mailing-lists.html
